global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "airflow"
    metrics_path: /metrics/
    static_configs:
      - targets: ["airflow-webserver:8080"]
        labels:
          service: "airflow-webserver"
      - targets: ["airflow-scheduler:8080"]
        labels:
          service: "airflow-scheduler"
      - targets: ["airflow-worker:8080"]
        labels:
          service: "airflow-worker"

  - job_name: "statsd-exporter"
    static_configs:
      - targets: ["statsd-exporter:9102"]
        labels:
          service: "statsd-exporter"

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
        labels:
          service: "postgres"

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
        labels:
          service: "redis" 